FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/

# Model bahar se mount hoga volume ke zariye
# COPY models/ ./models/  ← YEH HATAO

ENV MODEL_PATH=/app/models/model_final.pth

EXPOSE 8000
CMD ["uvicorn", "src.inference:app", "--host", "0.0.0.0", "--port", "8000"]